// <auto-generated />
namespace Tsingbo.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addimagefieldforarticle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addimagefieldforarticle));
        
        string IMigrationMetadata.Id
        {
            get { return "201210051054126_add-image-field-for-article"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
