// <auto-generated />
namespace Tsingbo.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ddd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ddd));
        
        string IMigrationMetadata.Id
        {
            get { return "201210040348227_ddd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
