//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.UI.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owen.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article list page number of records.
        /// </summary>
        public static string CatePagerCount {
            get {
                return ResourceManager.GetString("CatePagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments pagination number of records.
        /// </summary>
        public static string CommentPagerCount {
            get {
                return ResourceManager.GetString("CommentPagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format is wrong.
        /// </summary>
        public static string Common_Reg_Msg {
            get {
                return ResourceManager.GetString("Common_Reg_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be filled.
        /// </summary>
        public static string Common_Required_Msg {
            get {
                return ResourceManager.GetString("Common_Required_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article reproduced Category Id set eg.(1,2,3).
        /// </summary>
        public static string ContributorCateIds {
            get {
                return ResourceManager.GetString("ContributorCateIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by &lt;a href=&quot;http://www.yqhome.net/&quot; target=&quot;_blank&quot;&gt;YQBlog&lt;/a&gt;.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total number of Decoration.
        /// </summary>
        public static string DecorateImgCount {
            get {
                return ResourceManager.GetString("DecorateImgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Language.
        /// </summary>
        public static string DefaultLang {
            get {
                return ResourceManager.GetString("DefaultLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICP.
        /// </summary>
        public static string Icp {
            get {
                return ResourceManager.GetString("Icp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home page the number of records.
        /// </summary>
        public static string IndexPagerCount {
            get {
                return ResourceManager.GetString("IndexPagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-us.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of characters of the summary information.
        /// </summary>
        public static string MaxSummaryCount {
            get {
                return ResourceManager.GetString("MaxSummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a number.
        /// </summary>
        public static string MustNum {
            get {
                return ResourceManager.GetString("MustNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message paging number of records.
        /// </summary>
        public static string NotePagerCount {
            get {
                return ResourceManager.GetString("NotePagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format requirements: eg 200x150, 90x60.
        /// </summary>
        public static string ThumbnailFormat {
            get {
                return ResourceManager.GetString("ThumbnailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Thumbnail settings.
        /// </summary>
        public static string ThumbnailInfo {
            get {
                return ResourceManager.GetString("ThumbnailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en-us.
        /// </summary>
        public static string UrlPath {
            get {
                return ResourceManager.GetString("UrlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Introduction.
        /// </summary>
        public static string WebDescription {
            get {
                return ResourceManager.GetString("WebDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site path.
        /// </summary>
        public static string WebPath {
            get {
                return ResourceManager.GetString("WebPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        public static string Webtitle {
            get {
                return ResourceManager.GetString("Webtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL.
        /// </summary>
        public static string Weburl {
            get {
                return ResourceManager.GetString("Weburl", resourceCulture);
            }
        }
    }
}
