//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Models.Article {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Article {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Article() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Models.Article.Article", typeof(Article).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CateId {
            get {
                return ResourceManager.GetString("CateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail can not more than 30 characters.
        /// </summary>
        public static string Email_Length_Msg {
            get {
                return ResourceManager.GetString("Email_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to recommend.
        /// </summary>
        public static string IsCommend {
            get {
                return ResourceManager.GetString("IsCommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether to Top.
        /// </summary>
        public static string IsTop {
            get {
                return ResourceManager.GetString("IsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reply.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename of the page.
        /// </summary>
        public static string ReName {
            get {
                return ResourceManager.GetString("ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename of the page can not more than 60 characters.
        /// </summary>
        public static string ReName_Length_Msg {
            get {
                return ResourceManager.GetString("ReName_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether or not to allow comments.
        /// </summary>
        public static string ReplyPermit {
            get {
                return ResourceManager.GetString("ReplyPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Description.
        /// </summary>
        public static string SeoDescription {
            get {
                return ResourceManager.GetString("SeoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Description can not more than 1000 characters.
        /// </summary>
        public static string SeoDescription_Length_Msg {
            get {
                return ResourceManager.GetString("SeoDescription_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Keywords.
        /// </summary>
        public static string Seokeywords {
            get {
                return ResourceManager.GetString("Seokeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Keywords can not more than 500 characters.
        /// </summary>
        public static string Seokeywords_Length_Msg {
            get {
                return ResourceManager.GetString("Seokeywords_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Metas.
        /// </summary>
        public static string SeoMetas {
            get {
                return ResourceManager.GetString("SeoMetas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Metas can not more than 1000 characters.
        /// </summary>
        public static string SeoMetas_Length_Msg {
            get {
                return ResourceManager.GetString("SeoMetas_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string SeoTitle {
            get {
                return ResourceManager.GetString("SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title can not more than 500 characters.
        /// </summary>
        public static string SeoTitle_Length_Msg {
            get {
                return ResourceManager.GetString("SeoTitle_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary can not more than 400 characters.
        /// </summary>
        public static string Summary_Length_Msg {
            get {
                return ResourceManager.GetString("Summary_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags (multiple tags with &apos;,&apos;  to separate).
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags can not more than 50 characters.
        /// </summary>
        public static string Tags_Length_Msg {
            get {
                return ResourceManager.GetString("Tags_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title can not more than 100 characters.
        /// </summary>
        public static string Title_Length_Msg {
            get {
                return ResourceManager.GetString("Title_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url can not more than 100 characters.
        /// </summary>
        public static string Url_Length_Msg {
            get {
                return ResourceManager.GetString("Url_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en-us.
        /// </summary>
        public static string UrlPath {
            get {
                return ResourceManager.GetString("UrlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName can not more than 20 characters.
        /// </summary>
        public static string UserName_Length_Msg {
            get {
                return ResourceManager.GetString("UserName_Length_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string UtcCreationDate {
            get {
                return ResourceManager.GetString("UtcCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modification Date.
        /// </summary>
        public static string UtcLastModificationDate {
            get {
                return ResourceManager.GetString("UtcLastModificationDate", resourceCulture);
            }
        }
    }
}
